# Generated by Django 4.0.3 on 2022-04-23 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
