# Generated by Django 4.0.3 on 2022-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(default=1, upload_to='coment/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
