# Generated by Django 4.0.3 on 2022-04-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='table',
            name='hevy',
        ),
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
